# Generated by Django 2.1.2 on 2018-10-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField()),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('cover', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='images/', width_field='width_field')),
            ],
        ),
    ]
