# Generated by Django 2.1.1 on 2018-10-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('finished', models.BooleanField()),
                ('institution', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=50)),
                ('url_address', models.URLField()),
            ],
        ),
    ]
