# Generated by Django 2.1.1 on 2018-10-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='instructor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
